routes/web.php
<?php

/*
 *
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {return view('auth.login'); });

Route::group(['middleware' => ['get.menu']], function () {
    Route::get('/dashboard', function () {return view('dashboard.homepage'); })->name('index');
    Route::group(['middleware' => ['role:user']], function () {
    Route::resource('refrigerator', 'RefrigeratorController', ['names' => 'dashboard.refrigerator']);
    Route::resource('receptions', 'ReceptionController', ['names' => 'dashboard.reception']);
    Route::resource('products', 'ProductController', ['names' => 'dashboard.product']);
    Route::get('/store/{id}', 'StoreController@show');


        Route::get('/404', function () {        return view('dashboard.404'); });
        Route::get('/500', function () {        return view('dashboard.500'); });
//
        Route::prefix('buttons')->group(function () {
            Route::get('/buttons', function(){          return view('dashboard.buttons.buttons'); });
            Route::get('/button-group', function(){     return view('dashboard.buttons.button-group'); });
            Route::get('/dropdowns', function(){        return view('dashboard.buttons.dropdowns'); });
            Route::get('/brand-buttons', function(){    return view('dashboard.buttons.brand-buttons'); });
        });
        Route::prefix('icon')->group(function () {  // word: "icons" - not working as part of adress
            Route::get('/coreui-icons', function(){         return view('dashboard.icons.coreui-icons'); });
            Route::get('/flags', function(){                return view('dashboard.icons.flags'); });
            Route::get('/brands', function(){               return view('dashboard.icons.brands'); });
        });
        Route::prefix('notifications')->group(function () {
            Route::get('/alerts', function(){   return view('dashboard.notifications.alerts'); });
            Route::get('/badge', function(){    return view('dashboard.notifications.badge'); });
            Route::get('/modals', function(){   return view('dashboard.notifications.modals'); });
        });
        //Route::resource('notes', 'NotesController');
    });


    Route::resource('resource/{table}/resource', 'ResourceController')->names([
        'index'     => 'resource.index',
        'create'    => 'resource.create',
        'store'     => 'resource.store',
        'show'      => 'resource.show',
        'edit'      => 'resource.edit',
        'update'    => 'resource.update',
        'destroy'   => 'resource.destroy'
    ]);

    Route::group(['middleware' => ['role:admin']], function () {
        Route::resource('bread',  'BreadController');   //create BREAD (resource)
        Route::resource('users',        'UsersController')->except( ['create', 'store'] );
        Route::resource('roles',        'RolesController');
        Route::resource('mail',        'MailController');
        Route::get('prepareSend/{id}',        'MailController@prepareSend')->name('prepareSend');
        Route::post('mailSend/{id}',        'MailController@send')->name('mailSend');
        Route::get('/roles/move/move-up',      'RolesController@moveUp')->name('roles.up');
        Route::get('/roles/move/move-down',    'RolesController@moveDown')->name('roles.down');
        Route::prefix('menu/element')->group(function () {
            /* login */
            Route::get('/move',             'MenuElementController@index')->name('menu.index');
            Route::get('/move-up',      'MenuElementController@moveUp')->name('menu.up');
            Route::get('/move-down',    'MenuElementController@moveDown')->name('menu.down');
            Route::get('/create',       'MenuElementController@create')->name('menu.create');
            Route::post('/store',       'MenuElementController@store')->name('menu.store');
            Route::get('/get-parents',  'MenuElementController@getParents');
            Route::get('/edit',         'MenuElementController@edit')->name('menu.edit');
            Route::post('/update',      'MenuElementController@update')->name('menu.update');
            Route::get('/show',         'MenuElementController@show')->name('menu.show');
            Route::get('/delete',       'MenuElementController@delete')->name('menu.delete');
        });
        Route::prefix('menu/menu')->group(function () {
            Route::get('/menu',         'MenuController@index')->name('menu.menu.index');
            Route::get('/create',   'MenuController@create')->name('menu.menu.create');
            Route::post('/store',   'MenuController@store')->name('menu.menu.store');
            Route::get('/edit',     'MenuController@edit')->name('menu.menu.edit');
            Route::post('/update',  'MenuController@update')->name('menu.menu.update');
            Route::get('/delete',   'MenuController@delete')->name('menu.menu.delete');
        });

    });
});

resources/views/dashboard/shared/breadcrumb.blade.php
        <!-- Breadcrumb-->
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <?php $segments = ''; ?>
            @for($i = 1; $i <= count(Request::segments()); $i++)
                <?php $segments .= '/'. Request::segment($i); ?>
                @if($i < count(Request::segments()))
                    <li class="breadcrumb-item">{{ Request::segment($i) }}</li>
                @else
                    <li class="breadcrumb-item active">{{ Request::segment($i) }}</li>
                @endif
            @endfor
          <!-- Breadcrumb Menu-->
          <li class="breadcrumb-menu d-md-down-none">
            <div class="btn-group" role="group" aria-label="Button group">
              <a class="btn" href="#">
                <i class="icon-speech"></i>
              </a>
              <a class="btn" href="./">
                <i class="icon-graph"></i>  Dashboard</a>
              <a class="btn" href="#">
                <i class="icon-settings"></i>  Settings</a>
            </div>
          </li>
        </ol>

resources/views/dashboard/shared/footer.blade.php
<footer class="c-footer">
  <div class="mx-auto">Powered by&nbsp;<a target="_blank" href="https://www.web-ex.tech/">Webex Technologies</a></div>
</footer>

resources/views/dashboard/shared/header.blade.php
    <div class="c-wrapper">
      <header class="c-header c-header-light c-header-fixed c-header-with-subheader">
        <button class="c-header-toggler c-class-toggler d-lg-none mr-auto" type="button" data-target="#sidebar" data-class="c-sidebar-show"><span class="c-header-toggler-icon"></span></button><a class="c-header-brand d-sm-none" href="#"><img class="c-header-brand" src="{{ url('/assets/brand/coreui-base.svg" width="97" height="46" alt="CoreUI Logo"></a>
        <button class="c-header-toggler c-class-toggler ml-3 d-md-down-none" type="button" data-target="#sidebar" data-class="c-sidebar-lg-show" responsive="true"><span class="c-header-toggler-icon"></span></button>
        <?php
        ?>
        <ul class="c-header-nav ml-auto mr-4">

          <li class="c-header-nav-item dropdown"><a class="c-header-nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
              <div class="c-avatar"><img class="c-avatar-img" src="{{ url('/assets/img/avatars/6.jpg') }}" alt="user@email.com"></div>
            </a>
            <div class="dropdown-menu dropdown-menu-right pt-0">
              <div class="dropdown-header bg-light py-2"><strong>Account</strong></div><a class="dropdown-item" href="#">

                <svg class="c-icon mr-2">
                  <use xlink:href="{{ url('/icons/sprites/free.svg#cil-account-logout') }}"></use>
                </svg><form action="{{ url('/logout') }}" method="POST"> @csrf <button type="submit" class="btn btn-ghost-dark btn-block">Logout</button></form></a>
            </div>
          </li>
        </ul>
        <div class="c-subheader px-3">
          <ol class="breadcrumb border-0 m-0">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <?php $segments = ''; ?>
            @for($i = 1; $i <= count(Request::segments()); $i++)
                <?php $segments .= '/'. Request::segment($i); ?>
                @if($i < count(Request::segments()))
                    <li class="breadcrumb-item">{{ Request::segment($i) }}</li>
                @else
                    <li class="breadcrumb-item active">{{ Request::segment($i) }}</li>
                @endif
            @endfor
          </ol>
        </div>
    </header>

resources/views/dashboard/shared/nav-admin.blade.php
     dededexxadsxs <div class="c-sidebar-brand"><img class="c-sidebar-brand-full" src="/assets/brand/coreui-base-white.svg" width="118" height="46" alt="CoreUI Logo"><img class="c-sidebar-brand-minimized" src="assets/brand/coreui-signet-white.svg" width="118" height="46" alt="CoreUI Logo"></div>
      <nav class="c-sidebar-nav">
        <ul class="c-nav">
          <li class="c-nav-item"><a class="c-nav-link" href="/">
              <svg class="c-nav-icon">
                <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-speedometer"></use>
              </svg> Dashboard<span class="badge badge-info">NEW</span></a></li>
          <li class="c-nav-title">Theme</li>
          <li class="c-nav-item"><a class="c-nav-link" href="/colors">
              <svg class="c-nav-icon">
                <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-drop1"></use>
              </svg> Colors 3sw</a></li>
          <li class="c-nav-item"><a class="c-nav-link" href="/typography">
              <svg class="c-nav-icon">
                <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-pencil"></use>
              </svg> Typography</a></li>
          <li class="c-nav-title">Components</li>
          <li class="c-nav-item c-nav-dropdown"><a class="c-nav-link c-nav-dropdown-toggle" href="#">
              <svg class="c-nav-icon">
                <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-puzzle"></use>
              </svg> Base</a>
            <ul class="c-nav-dropdown-items">
              <li class="c-nav-item"><a class="c-nav-link" href="/base/breadcrumb"><span class="c-nav-icon"></span> Breadcrumb</a></li>
              <li class="c-nav-item"><a class="c-nav-link" href="/base/cards"><span class="c-nav-icon"></span> Cards</a></li>
              <li class="c-nav-item"><a class="c-nav-link" href="/base/carousel"><span class="c-nav-icon"></span> Carousel</a></li>
              <li class="c-nav-item"><a class="c-nav-link" href="/base/collapse"><span class="c-nav-icon"></span> Collapse</a></li>
              <li class="c-nav-item"><a class="c-nav-link" href="/base/forms"><span class="c-nav-icon"></span> Forms</a></li>
              <li class="c-nav-item"><a class="c-nav-link" href="/base/jumbotron"><span class="c-nav-icon"></span> Jumbotron</a></li>
              <li class="c-nav-item"><a class="c-nav-link" href="/base/list-group"><span class="c-nav-icon"></span> List group</a></li>
              <li class="c-nav-item"><a class="c-nav-link" href="/base/navs"><span class="c-nav-icon"></span> Navs</a></li>
              <li class="c-nav-item"><a class="c-nav-link" href="/base/pagination"><span class="c-nav-icon"></span> Pagination</a></li>
              <li class="c-nav-item"><a class="c-nav-link" href="/base/popovers"><span class="c-nav-icon"></span> Popovers</a></li>
              <li class="c-nav-item"><a class="c-nav-link" href="/base/progress"><span class="c-nav-icon"></span> Progress</a></li>
              <li class="c-nav-item"><a class="c-nav-link" href="/base/scrollspy"><span class="c-nav-icon"></span> Scrollspy</a></li>
              <li class="c-nav-item"><a class="c-nav-link" href="/base/switches"><span class="c-nav-icon"></span> Switches</a></li>
              <li class="c-nav-item"><a class="c-nav-link" href="/base/tables"><span class="c-nav-icon"></span> Tables</a></li>
              <li class="c-nav-item"><a class="c-nav-link" href="/base/tabs"><span class="c-nav-icon"></span> Tabs</a></li>
              <li class="c-nav-item"><a class="c-nav-link" href="/base/tooltips"><span class="c-nav-icon"></span> Tooltips</a></li>
            </ul>
          </li>
          <li class="c-nav-item c-nav-dropdown"><a class="c-nav-link c-nav-dropdown-toggle" href="#">
              <svg class="c-nav-icon">
                <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-cursor"></use>
              </svg> Buttons</a>
            <ul class="c-nav-dropdown-items">
              <li class="c-nav-item"><a class="c-nav-link" href="/buttons/buttons"><span class="c-nav-icon"></span> Buttons</a></li>
              <li class="c-nav-item"><a class="c-nav-link" href="/buttons/button-group"><span class="c-nav-icon"></span> Buttons Group</a></li>
              <li class="c-nav-item"><a class="c-nav-link" href="/buttons/dropdowns"><span class="c-nav-icon"></span> Dropdowns</a></li>
              <li class="c-nav-item"><a class="c-nav-link" href="/buttons/brand-buttons"><span class="c-nav-icon"></span> Brand Buttons</a></li>
            </ul>
          </li>
          <li class="c-nav-item"><a class="c-nav-link" href="/charts">
              <svg class="c-nav-icon">
                <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-chart-pie"></use>
              </svg> Charts</a></li>
          <li class="c-nav-item c-nav-dropdown"><a class="c-nav-link c-nav-dropdown-toggle" href="#">
              <svg class="c-nav-icon">
                <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-star"></use>
              </svg> Icons</a>
            <ul class="c-nav-dropdown-items">
              <li class="c-nav-item"><a class="c-nav-link" href="/icon/coreui-icons"><span class="c-nav-icon"></span> CoreUI Icons<span class="badge badge-success">Free</span></a></li>
              <li class="c-nav-item"><a class="c-nav-link" href="/icon/flags"><span class="c-nav-icon"></span> Flags</a></li>
              <li class="c-nav-item"><a class="c-nav-link" href="/icon/brands"><span class="c-nav-icon"></span> Brands</a></li>
            </ul>
          </li>
          <li class="c-nav-item c-nav-dropdown"><a class="c-nav-link c-nav-dropdown-toggle" href="#">
              <svg class="c-nav-icon">
                <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-bell"></use>
              </svg> Notifications</a>
            <ul class="c-nav-dropdown-items">
              <li class="c-nav-item"><a class="c-nav-link" href="/notifications/alerts"><span class="c-nav-icon"></span> Alerts</a></li>
              <li class="c-nav-item"><a class="c-nav-link" href="/notifications/badge"><span class="c-nav-icon"></span> Badge</a></li>
              <li class="c-nav-item"><a class="c-nav-link" href="/notifications/modals"><span class="c-nav-icon"></span> Modals</a></li>
            </ul>
          </li>
          <li class="c-nav-item"><a class="c-nav-link" href="/widgets">
              <svg class="c-nav-icon">
                <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-calculator"></use>
              </svg> Widgets<span class="badge badge-info">NEW</span></a></li>
          <li class="c-nav-divider"></li>
          <li class="c-nav-title">Extras</li>
          <li class="c-nav-item c-nav-dropdown"><a class="c-nav-link c-nav-dropdown-toggle" href="#">
              <svg class="c-nav-icon">
                <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-star"></use>
              </svg> Pages</a>
            <ul class="c-nav-dropdown-items">
              <li class="c-nav-item"><a class="c-nav-link" href="/login" target="_top">
                  <svg class="c-nav-icon">
                    <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-account-logout"></use>
                  </svg> Login</a></li>
              <li class="c-nav-item"><a class="c-nav-link" href="/register" target="_top">
                  <svg class="c-nav-icon">
                    <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-account-logout"></use>
                  </svg> Register</a></li>
              <li class="c-nav-item"><a class="c-nav-link" href="/404" target="_top">
                  <svg class="c-nav-icon">
                    <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-bug"></use>
                  </svg> Error 404</a></li>
              <li class="c-nav-item"><a class="c-nav-link" href="/500" target="_top">
                  <svg class="c-nav-icon">
                    <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-bug"></use>
                  </svg> Error 500</a></li>
            </ul>
          </li>
          <li class="c-nav-item mt-auto"><a class="c-nav-link c-nav-link-success" href="https://coreui.io" target="_top">
              <svg class="c-nav-icon">
                <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-cloud-download"></use>
              </svg> Download CoreUI</a></li>
          <li class="c-nav-item"><a class="c-nav-link c-nav-link-danger" href="https://coreui.io/pro/" target="_top">
              <svg class="c-nav-icon">
                <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-layers"></use>
              </svg> Try CoreUI<strong>PRO</strong></a></li>
        </ul>
      </nav>
      <button class="c-sidebar-minimizer c-class-toggler" type="button" data-target="_parent" data-class="c-sidebar-minimized"></button>
    </div>

resources/views/dashboard/shared/nav-builder.blade.php
<?php
/*
    $data = $menuel['elements']
*/

if(!function_exists('renderDropdown')){
    function renderDropdown($data){
        if(array_key_exists('slug', $data) && $data['slug'] === 'dropdown'){
            echo '<li class="c-sidebar-nav-dropdown">';
            echo '<a class="c-sidebar-nav-dropdown-toggle" href="#">';
            if($data['hasIcon'] === true && $data['iconType'] === 'coreui'){
                echo '<i class="' . $data['icon'] . ' c-sidebar-nav-icon"></i>';
            }
            echo $data['name'] . '</a>';
            echo '<ul class="c-sidebar-nav-dropdown-items">';
            renderDropdown( $data['elements'] );
            echo '</ul></li>';
        }else{
            for($i = 0; $i < count($data); $i++){
                if( $data[$i]['slug'] === 'link' ){
                    echo '<li class="c-sidebar-nav-item">';
                    echo '<a class="c-sidebar-nav-link" href="' . url($data[$i]['href']) . '">';
                    echo '<span class="c-sidebar-nav-icon"></span>' . $data[$i]['name'] . '</a></li>';
                }elseif( $data[$i]['slug'] === 'dropdown' ){
                    renderDropdown( $data[$i] );
                }
            }
        }
    }
}
?>
        <div class="c-sidebar-brand">
            <img class="c-sidebar-brand-full" src="{{ url('/assets/brand/coreui-base-white.svg') }}" width="118" height="46" alt="CoreUI Logo">
            <img class="c-sidebar-brand-minimized" src="{{ url('assets/brand/coreui-signet-white.svg') }}" width="118" height="46" alt="CoreUI Logo">
        </div>
        <ul class="c-sidebar-nav">
            <li class="c-sidebar-nav-item">
                <a class="c-sidebar-nav-link" href="{{ route('dashboard.product.index')}}">
                    <i class="cil-drop1 c-sidebar-nav-icon"></i>
                    Продукт
                </a>
            </li>
            <li class="c-sidebar-nav-item">
                <a class="c-sidebar-nav-link" href="{{ route('dashboard.refrigerator.index')}}">
                    <i class="c-icon cil-fridge c-sidebar-nav-icon"></i>
                    Холодильник
                </a>
            </li>
            <li class="c-sidebar-nav-item">
                <a class="c-sidebar-nav-link" href="{{ route('dashboard.reception.index') }}">

                    <i class="c-icon c-sidebar-nav-icon cil-notes"></i>
                    Рецепт
                </a>
            </li>
        </ul>
        <button class="c-sidebar-minimizer c-class-toggler" type="button" data-target="_parent" data-class="c-sidebar-minimized"></button>
    </div>

resources/views/dashboard/shared/nav.blade.php
      <div class="c-sidebar-brand"><img class="c-sidebar-brand-full" src="/assets/brand/coreui-base-white.svg" width="118" height="46" alt="CoreUI Logo"><img class="c-sidebar-brand-minimized" src="assets/brand/coreui-signet-white.svg" width="118" height="46" alt="CoreUI Logo"></div>
      <nav class="c-sidebar-nav">
        <ul class="c-nav">
          <li class="c-nav-item"><a class="c-nav-link" href="/">
              <svg class="c-nav-icon">
                <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-speedometer"></use>
              </svg> Dashboard<span class="badge badge-info">NEW</span></a></li>

              <li class="c-nav-item"><a class="c-nav-link" href="/login" target="_top">
                  <svg class="c-nav-icon">
                    <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-account-logout"></use>
                  </svg> Login</a></li>
              <li class="c-nav-item"><a class="c-nav-link" href="/register" target="_top">
                  <svg class="c-nav-icon">
                    <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-account-logout"></use>
                  </svg> Register</a></li>

          <li class="c-nav-item mt-auto"><a class="c-nav-link c-nav-link-success" href="https://coreui.io" target="_top">
              <svg class="c-nav-icon">
                <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-cloud-download"></use>
              </svg> Download CoreUI</a></li>
          <li class="c-nav-item"><a class="c-nav-link c-nav-link-danger" href="https://coreui.io/pro/" target="_top">
              <svg class="c-nav-icon">
                <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-layers"></use>
              </svg> Try CoreUI<strong>PRO</strong></a></li>
        </ul>
      </nav>
      <button class="c-sidebar-minimizer c-class-toggler" type="button" data-target="_parent" data-class="c-sidebar-minimized"></button>
    </div>

resources/views/dashboard/shared/universal-info.blade.php
@extends('dashboard.base')

@section('content')


<div class="container-fluid">
  <div class="fade-in">
    <div class="row">
      <div class="col-sm-12">
        <div class="card">
            <div class="card-header">
                @if(Session::has('title'))
                <h4>{{ Session::get('title') }}</h4>
                @endif
            </div>
            <div class="card-body">

                @if(Session::has('message'))
                    <div class="alert alert-success" role="alert">{{ Session::get('message') }}</div>
                @else
                    <div class="alert alert-success" role="alert">Success</div>
                @endif
                
                @if(Session::has('back'))
                    @if(Session::has('backParams'))
                        <a href="{{ route( Session::get('back'), Session::get('backParams') ) }}" class="btn btn-lg btn-primary">Return</a>
                    @else
                        <a href="{{ route( Session::get('back') ) }}" class="btn btn-lg btn-primary">Return</a>
                    @endif
                @endif

            </div>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection

@section('javascript')


@endsection